### ISSUE TITLE
Index error for `utils.slice_between_points` when using last time step

### ISSUE THREAD

**Issue by JoannaChang** [NeuralAnalysis/PyalData#103]
If the `end_point_name` for `restrict_to_interval` or `slice_between_points` is the last time point of the trial (e.g. 'idx_trial_end'), then there is an error for slicing

`slice(trial[start_point_name]-before, trial[end_point_name]+after+1)`

since the index `trial[end_point_name]+1` does not exist.

**Comment by bagibence** [comment]
Sorry for not addressing this earlier. Is this still an issue? I tried replicating the problem but it seems to work for me:

<img width="724" alt="Screenshot 2021-09-16 at 09 58 03" src="https://user-images.githubusercontent.com/17183496/133582959-f8f3e340-2427-471d-b634-b1eda4c462da.png">
