### ISSUE TITLE
New smoothing function is slower than previous one (for my data)

### ISSUE THREAD

**Issue by raeedcho** [NeuralAnalysis/PyalData#118]
A recent issue/pull request combo (https://github.com/mattperich/PyalData/issues/101 and https://github.com/mattperich/PyalData/pull/106) changed up the function underlying smoothing of signals (from `scipy.signal.convolve` to `scipy.ndimage.convolve1d`) in an attempt to make things faster by not looping and concatenating. Unfortunately, this change somehow makes smoothing run slower than before on my computer, but I'm not sure how that could be the case if it works faster for everyone else. Any ideas why that could be the case? Would it make sense to keep both methods and default to the new version, but have an option to change the backend function?

For reference, for one of my datasets, running `%timeit pyaldata.add_firing_rates(td,'smooth',std=0.05)` now gives 18.7 s ± 52.8 ms, whereas if I revert the change, it gives 4.55 s ± 113 ms--so it's now about 4x slower for me.

**Comment by bagibence** [comment]
I just had an idea what might cause this. Could it be that when you tested the new way of smoothing you also applied #117, but not when testing the old way?

I guess #117 slows down smoothing by making the filter longer. I just tested 3 versions on the same data with the following results:

<img width="418" alt="Screenshot 2021-09-15 at 15 41 19" src="https://user-images.githubusercontent.com/17183496/133455784-6dfeb423-5c52-4c21-8948-3306a06e4cf2.png">

**Comment by raeedcho** [comment]
I tested it with 5 and 10 std, but the old way was still far faster for
some reason. What does your output look like for the old smoothing with 10
std?

**Comment by bagibence** [comment]
That's weird. This is what I got today:

<img width="419" alt="Screenshot 2021-09-17 at 10 40 12" src="https://user-images.githubusercontent.com/17183496/133752704-1620f4ac-f72a-4cb4-9d80-e7792c63acb7.png">

Maybe your dataset is longer and they scale differently?

**Comment by raeedcho** [comment]
Based on your test and a few of mine, it does seem like the scale differently to different amounts of data, possibly. I've opened a pull request (https://github.com/NeuralAnalysis/PyalData/pull/130) to allow you to specify the backend, but have left the default as the new version so it doesn't hurt anyone else (hopefully).
