### ISSUE TITLE
Refractor code into smaller modules

### ISSUE THREAD

**Issue by bagibence** [NeuralAnalysis/PyalData#120]
@raeedcho already started this in #119, just moving the discussion here.

Now everything is dumped into big files, and we should partition it by functionality for better organization and easier navigation.

I guess this would also be the time to write some tests to make sure that the refractor doesn't break functionality?

**Comment by raeedcho** [comment]
I indeed thought about writing some unit tests, but realized that doing it right would take me some time that I didn't have at the moment. But it's a good idea! I suppose we would want to use Python's `unittest` package to write tests?

**Comment by bagibence** [comment]
Yes, or [pytest](https://docs.pytest.org/en/latest/) might be easier.

**Comment by AtMostafa** [comment]
ooh... brilliant idea. I'll try to test it soon :)

**Comment by bagibence** [comment]
I did dome work on this. It seems to work for my analysis code, but it would be great if you guys could test it, too.

**Comment by AtMostafa** [comment]
It works on my analyses as well :+1:

**Comment by bagibence** [comment]
Merged #119, so I'll close this for now.
New functionality should either go into the most appropriate module or into a new one.
